const mongoose = require('mongoose');
const User = require('./models/User');
const Book = require('./models/Book');
require('dotenv').config({ path: './config.env' });

const booksData = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set in the Jazz Age of the 1920s.",
    isbn: "9780743273565",
    price: 12.99,
    originalPrice: 15.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 180,
    publisher: "Scribner",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 50,
    ratings: { average: 4.2, count: 1250 },
    featured: true,
    bestseller: true,
    discount: 19
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "The story of young Scout Finch and her father Atticus in a racially divided Alabama town.",
    isbn: "9780446310789",
    price: 14.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 281,
    publisher: "Grand Central Publishing",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 75,
    ratings: { average: 4.5, count: 2100 },
    featured: true,
    bestseller: true
  },
  {
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel about totalitarianism, surveillance, and the manipulation of truth.",
    isbn: "9780451524935",
    price: 11.99,
    category: "Science Fiction",
    language: "English",
    format: "Paperback",
    pages: 328,
    publisher: "Signet",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 60,
    ratings: { average: 4.3, count: 1800 },
    featured: true,
    bestseller: true
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy novel about Bilbo Baggins, a hobbit who embarks on an adventure with thirteen dwarves.",
    isbn: "9780547928241",
    price: 16.99,
    category: "Fiction",
    language: "English",
    format: "Hardcover",
    pages: 366,
    publisher: "Houghton Mifflin Harcourt",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 40,
    ratings: { average: 4.4, count: 1600 },
    featured: true,
    bestseller: true
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel of manners that follows the emotional development of Elizabeth Bennet.",
    isbn: "9780141439518",
    price: 9.99,
    category: "Romance",
    language: "English",
    format: "Paperback",
    pages: 432,
    publisher: "Penguin Classics",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 55,
    ratings: { average: 4.1, count: 1400 },
    bestseller: true
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A novel about a young Andalusian shepherd who dreams of finding a worldly treasure.",
    isbn: "9780062315007",
    price: 15.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 208,
    publisher: "HarperOne",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 80,
    ratings: { average: 4.0, count: 2200 },
    featured: true,
    bestseller: true
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description: "A dystopian novel about a teenage girl who volunteers to take her sister's place in a televised battle.",
    isbn: "9780439023481",
    price: 14.99,
    category: "Young Adult",
    language: "English",
    format: "Paperback",
    pages: 374,
    publisher: "Scholastic",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 90,
    ratings: { average: 4.2, count: 2800 },
    featured: true,
    bestseller: true
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "A biography of Steve Jobs, the co-founder of Apple Inc.",
    isbn: "9781451648539",
    price: 19.99,
    category: "Biography",
    language: "English",
    format: "Hardcover",
    pages: 656,
    publisher: "Simon & Schuster",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 35,
    ratings: { average: 4.3, count: 1200 },
    featured: true,
    bestseller: true
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    description: "A guide about how tiny changes in behavior can result in remarkable outcomes.",
    isbn: "9780735211292",
    price: 16.99,
    category: "Self-Help",
    language: "English",
    format: "Hardcover",
    pages: 320,
    publisher: "Avery",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 85,
    ratings: { average: 4.5, count: 3200 },
    featured: true,
    bestseller: true
  },
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "A novel about a library between life and death where each book provides a chance to try another life.",
    isbn: "9780525559474",
    price: 14.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 288,
    publisher: "Viking",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 75,
    ratings: { average: 4.0, count: 2100 },
    featured: true,
    bestseller: true
  },
  // Additional Fiction Books
  {
    title: "Dune",
    author: "Frank Herbert",
    description: "A science fiction epic about politics, religion, and ecology on the desert planet Arrakis.",
    isbn: "9780441172719",
    price: 16.99,
    originalPrice: 19.99,
    category: "Science Fiction",
    language: "English",
    format: "Paperback",
    pages: 688,
    publisher: "Ace",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 45,
    ratings: { average: 4.6, count: 3500 },
    featured: true,
    bestseller: true,
    discount: 15
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description: "A psychological thriller about a woman who refuses to speak after allegedly murdering her husband.",
    isbn: "9781250301697",
    price: 13.99,
    category: "Thriller",
    language: "English",
    format: "Paperback",
    pages: 336,
    publisher: "Celadon Books",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 65,
    ratings: { average: 4.1, count: 2800 },
    bestseller: true
  },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description: "A coming-of-age mystery about a young woman who raised herself in the marshes of North Carolina.",
    isbn: "9780735219090",
    price: 15.99,
    originalPrice: 17.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 70,
    ratings: { average: 4.3, count: 4200 },
    featured: true,
    bestseller: true,
    discount: 11
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    description: "A reclusive Hollywood icon finally tells her story to an unknown journalist.",
    isbn: "9781501161933",
    price: 14.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 400,
    publisher: "Atria Books",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 55,
    ratings: { average: 4.4, count: 3800 },
    bestseller: true
  },
  {
    title: "Educated",
    author: "Tara Westover",
    description: "A memoir about a woman who grows up in a survivalist family and eventually earns a PhD from Cambridge.",
    isbn: "9780399590504",
    price: 16.99,
    category: "Biography",
    language: "English",
    format: "Hardcover",
    pages: 334,
    publisher: "Random House",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 40,
    ratings: { average: 4.5, count: 2900 },
    featured: true,
    bestseller: true
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    description: "The intimate memoir of the former First Lady of the United States.",
    isbn: "9781524763138",
    price: 18.99,
    originalPrice: 22.99,
    category: "Biography",
    language: "English",
    format: "Hardcover",
    pages: 448,
    publisher: "Crown",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 60,
    ratings: { average: 4.7, count: 5200 },
    featured: true,
    bestseller: true,
    discount: 17
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description: "A brief history of humankind from the Stone Age to the present.",
    isbn: "9780062316097",
    price: 17.99,
    category: "History",
    language: "English",
    format: "Paperback",
    pages: 464,
    publisher: "Harper",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 50,
    ratings: { average: 4.4, count: 4100 },
    featured: true,
    bestseller: true
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    description: "A counterintuitive approach to living a good life.",
    isbn: "9780062457714",
    price: 14.99,
    category: "Self-Help",
    language: "English",
    format: "Paperback",
    pages: 224,
    publisher: "HarperOne",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 80,
    ratings: { average: 4.2, count: 3600 },
    bestseller: true
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    description: "The classic guide to wealth and success, based on interviews with successful people.",
    isbn: "9781585424337",
    price: 12.99,
    originalPrice: 15.99,
    category: "Business",
    language: "English",
    format: "Paperback",
    pages: 320,
    publisher: "TarcherPerigee",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 45,
    ratings: { average: 4.1, count: 2700 },
    discount: 19
  },
  // More Fiction & Literature
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: "A powerful story of friendship, betrayal, and redemption set in Afghanistan.",
    isbn: "9781594631931",
    price: 15.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 371,
    publisher: "Riverhead Books",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 55,
    ratings: { average: 4.3, count: 3200 },
    bestseller: true
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    description: "A story about a young girl living in Nazi Germany, narrated by Death.",
    isbn: "9780375842207",
    price: 13.99,
    originalPrice: 16.99,
    category: "Fiction",
    language: "English",
    format: "Paperback",
    pages: 552,
    publisher: "Knopf Books",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 40,
    ratings: { average: 4.4, count: 2800 },
    featured: true,
    discount: 18
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    description: "A psychological thriller about a marriage gone terribly wrong.",
    isbn: "9780307588371",
    price: 14.99,
    category: "Thriller",
    language: "English",
    format: "Paperback",
    pages: 432,
    publisher: "Crown",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 65,
    ratings: { average: 4.0, count: 4500 },
    bestseller: true
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    description: "A gripping thriller about a journalist and a hacker investigating a decades-old disappearance.",
    isbn: "9780307454546",
    price: 15.99,
    category: "Mystery",
    language: "English",
    format: "Paperback",
    pages: 590,
    publisher: "Vintage",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 50,
    ratings: { average: 4.2, count: 3800 },
    bestseller: true
  },
  // Science & Technology
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description: "A landmark volume in science writing that explores the nature of the universe.",
    isbn: "9780553380163",
    price: 16.99,
    category: "Science",
    language: "English",
    format: "Paperback",
    pages: 256,
    publisher: "Bantam",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 35,
    ratings: { average: 4.3, count: 2100 },
    featured: true
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    isbn: "9780307887894",
    price: 17.99,
    originalPrice: 20.99,
    category: "Business",
    language: "English",
    format: "Hardcover",
    pages: 336,
    publisher: "Crown Business",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 40,
    ratings: { average: 4.2, count: 1800 },
    discount: 14
  },
  // Young Adult
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    description: "A love story about two teenagers who meet in a cancer support group.",
    isbn: "9780525478812",
    price: 12.99,
    category: "Young Adult",
    language: "English",
    format: "Paperback",
    pages: 313,
    publisher: "Dutton Books",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 70,
    ratings: { average: 4.3, count: 5200 },
    bestseller: true,
    newRelease: true
  },
  {
    title: "Divergent",
    author: "Veronica Roth",
    description: "In a dystopian Chicago, society is divided into five factions based on personality traits.",
    isbn: "9780062024039",
    price: 13.99,
    category: "Young Adult",
    language: "English",
    format: "Paperback",
    pages: 487,
    publisher: "Katherine Tegen Books",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 60,
    ratings: { average: 4.1, count: 3400 },
    bestseller: true
  },
  // Cooking & Lifestyle
  {
    title: "Salt, Fat, Acid, Heat",
    author: "Samin Nosrat",
    description: "Master the four fundamental elements of good cooking.",
    isbn: "9781476753836",
    price: 19.99,
    originalPrice: 24.99,
    category: "Cooking",
    language: "English",
    format: "Hardcover",
    pages: 480,
    publisher: "Simon & Schuster",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    stock: 30,
    ratings: { average: 4.6, count: 1900 },
    featured: true,
    discount: 20
  },
  // Poetry & Drama
  {
    title: "Milk and Honey",
    author: "Rupi Kaur",
    description: "A collection of poetry and prose about survival, healing, and love.",
    isbn: "9781449474256",
    price: 11.99,
    category: "Poetry",
    language: "English",
    format: "Paperback",
    pages: 208,
    publisher: "Andrews McMeel Publishing",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
    stock: 85,
    ratings: { average: 4.0, count: 2600 },
    bestseller: true,
    newRelease: true
  },
  // Travel
  {
    title: "Eat, Pray, Love",
    author: "Elizabeth Gilbert",
    description: "One woman's search for everything across Italy, India, and Indonesia.",
    isbn: "9780143038412",
    price: 15.99,
    category: "Travel",
    language: "English",
    format: "Paperback",
    pages: 352,
    publisher: "Penguin Books",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    stock: 45,
    ratings: { average: 3.9, count: 3100 },
    bestseller: true,
    newRelease: true
  },
  // Children's Books
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description: "The first book in the beloved Harry Potter series about a young wizard's adventures.",
    isbn: "9780439708180",
    price: 8.99,
    originalPrice: 10.99,
    category: "Children",
    language: "English",
    format: "Paperback",
    pages: 309,
    publisher: "Scholastic",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    stock: 100,
    ratings: { average: 4.8, count: 8500 },
    featured: true,
    bestseller: true,
    discount: 18
  },
  {
    title: "Wonder",
    author: "R.J. Palacio",
    description: "A story about a boy with facial differences who enters fifth grade.",
    isbn: "9780375869020",
    price: 9.99,
    category: "Children",
    language: "English",
    format: "Paperback",
    pages: 315,
    publisher: "Knopf Books",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    stock: 75,
    ratings: { average: 4.7, count: 4200 },
    featured: true,
    bestseller: true
  }
];

const adminUser = {
  name: "Admin User",
  email: "admin@bookstore.com",
  password: "admin123",
  role: "admin",
  phone: "+1234567890"
};

mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    console.log('Connected to MongoDB');
    try {
      await User.deleteMany({});
      await Book.deleteMany({});
      
      const admin = await User.create(adminUser);
      console.log('Admin user created:', admin.email);

      const booksWithCreator = booksData.map(book => ({
        ...book,
        createdBy: admin._id
      }));

      const books = await Book.create(booksWithCreator);
      console.log(`Created ${books.length} books`);

      const testUser = await User.create({
        name: "Test User",
        email: "test@bookstore.com",
        password: "test123",
        role: "user",
        phone: "+1987654321"
      });
      console.log('Test user created:', testUser.email);

      console.log('\nTest Accounts:');
      console.log('Admin - Email: admin@bookstore.com, Password: admin123');
      console.log('User - Email: test@bookstore.com, Password: test123');

    } catch (error) {
      console.error('Error seeding data:', error);
    }
    process.exit(0);
  })
  .catch((err) => {
    console.error('MongoDB connection error:', err);
    process.exit(1);
  }); 